theme = "anubis"
baseURL = "https://å.xyz/"
languageCode = "fi"
title = "Å.xyz"
disableKinds = ["taxonomy", "taxonomyTerm"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
